# Generated by Django 3.2.11 on 2023-09-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingmodel',
            old_name='address',
            new_name='address_line_one',
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='address_line_two',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
