# Generated by Django 3.2.11 on 2023-09-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20230930_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='garage',
            field=models.BooleanField(default=False),
        ),
    ]
