# Generated by Django 3.2.11 on 2023-09-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listingmodel_garage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='sqft',
            field=models.IntegerField(blank=True),
        ),
    ]
