# Generated by Django 3.2.11 on 2023-09-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20230930_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='bathrooms',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='lot_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
