# Generated by Django 3.2.11 on 2023-10-01 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0006_auto_20230930_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='landlord',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.clientmodel'),
            preserve_default=False,
        ),
    ]
