# Generated by Django 3.2.11 on 2023-10-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listingmodel_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyapplicationmodel',
            name='occupants',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
