# Generated by Django 3.2.11 on 2023-10-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_propertyapplicationmodel_occupants'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyapplicationmodel',
            name='phone_number',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
