# Generated by Django 3.2.11 on 2023-10-01 15:21

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_propertyapplicationmodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyapplicationmodel',
            name='move_in_date',
            field=models.DateField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
