# Generated by Django 3.2.11 on 2023-10-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_propertyapplicationmodel_move_in_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyViewing',
            new_name='PropertyViewingModel',
        ),
    ]
